name: Build dev

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:

    #    runs-on: self-hosted
    runs-on: ${{ matrix.operating-system }}

    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['8.1']

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Setup PHP, with composer and extensions"
        uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, xml, ctype, iconv, intl
          coverage: xdebug #optional
        env:
          runner: ${{ matrix.operating-system }}

      - name: "Validate composer.json and composer.lock"
        run: composer validate

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: "Install dependencies"
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: |
          composer update --prefer-dist --no-progress
          npm ci
          npm install --force

      - name: "run analyse"
        run: make analyse-ci

      - name: "build npm"
        run: npm run build

      - name: "Create database"
        run: make load-db-test

      - name: "run tests"
        run: make tests
